import "./globals.css";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import NavBar from "@/components/NavBar";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-gray-600">
      <head>
        <script src="https://unpkg.com/split-type"></script>
      </head>
      <body className={outfit.className}>
        <div className="bg-gray-600">
          <NavBar />
          <main className="ml-16">{children}</main>
        </div>
      </body>
    </html>
  );
}
